# Data Extraction from MIMIC.

### Contents:

* (A) Locating the required data
* (B) Extracting the data
* (C) Post-processing of data (involves combining with cohort information from 'cohort_selection_mimic.ipynb')

We use two mysql libraries:

* 'sql' is simple for scripting, with line/cell magic. 
* 'MySQLdb' is required for more complex operations (e.g. parameter binding with python lists, and storing results directly in graphlab/python dataframes).


In [2]:
import numpy as np
import pickle
from collections import OrderedDict
import pandas as pd

In [3]:
from google.cloud import bigquery
# Construct a BigQuery client object.
client = bigquery.Client()


In [4]:
list(client.list_datasets())

In [2]:
query = """
SELECT *
FROM `physionet-data.mimiciii_clinical.icustays`
WHERE icustay_id < 200100
ORDER BY icustay_id
"""
query_job = client.query(query)

In [3]:
df = query_job.to_dataframe()

In [7]:
import pandas as pd
pd.read_gbq??

In [2]:
%load_ext sql
%sql mysql://root:mysql2016@localhost/MIMIC?unix_socket=/run/mysqld/mysqld.sock
%sql USE MIMIC

/home/rusty/anaconda3/lib/python2.7/site-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated since IPython 4.0. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
/home/rusty/anaconda3/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")


This non-commercial license of GraphLab Create for academic use is assigned to cm1788@bristol.ac.uk and will expire on October 04, 2019.


[INFO] graphlab.cython.cy_server: GraphLab Create v2.1 started. Logging: /tmp/graphlab_server_1553264788.log


0 rows affected.


/home/rusty/anaconda3/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/base.py:1569: Warning: '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead
  cursor.execute('SELECT @@tx_isolation')


[]

### (A) Locating the required data.

A number of different variables are required to assess the nurse led discharge (NLD) criteria. Here we locate the ITEMIDs corresponding to these variables, which will be used to extract patient data from chartevents.

For simplicity we focus on (dbsource=)'Metavision' only since data storage within 'Carevue' is less coherent. Because the study compares with a general intensive care unit (GICU) from the UK, we take only patients with (first_careunit=)'MICU' or 'SICU' since this patient subset approximately corresponds to the GICU population.

The required variables are:

#### To locate these variables we proceed as follows: 

We define these search terms:

And search for ITEMIDS with LABELS that match the search terms using the following query (replacing the search terms for each variable with those above):

In [9]:
client.get_dataset??

In [14]:
query = """SELECT
  *
FROM
  `physionet-data.mimiciii_clinical.d_items`
WHERE
  LOWER(LABEL) LIKE '%fraction%'
  OR LOWER(LABEL) LIKE '%fio2%'
  AND DBSOURCE='metavision'"""
df = client.query(query).to_dataframe()
df

ROW_ID  ITEMID                 LABEL        ABBREVIATION    DBSOURCE  \
0   14083  225628    CK-MB fraction (%)  CK-MB fraction (%)  metavision   
1   12804  223835  Inspired O2 Fraction                FiO2  metavision   
2   14515  226754     FiO2ApacheIIValue   FiO2ApacheIIValue  metavision   
3   14685  227008     Ejection Fraction   Ejection Fraction  metavision   
4   14686  227009     FiO2_ApacheIV_old   FiO2_ApacheIV_old  metavision   
5   14687  227010         FiO2_ApacheIV       FiO2_ApacheIV  metavision   

       LINKSTO                CATEGORY UNITNAME PARAM_TYPE CONCEPTID  
0  chartevents                    Labs     None    Numeric      None  
1  chartevents             Respiratory     None    Numeric      None  
2  chartevents      Scores - APACHE II        %    Numeric      None  
3  chartevents  Scores - APACHE IV (2)        %    Numeric      None  
4  chartevents  Scores - APACHE IV (2)     None    Numeric      None  
5  chartevents  Scores - APACHE IV (2)        %    Numeric      None

For each variable we visually inspect the search ouptut and select the ITEMS that appear relevant. 

*For example, for FiO2 we select 226754, 227009, 227010,223835 as candidates.*

We then measure the approximate frequnecy of the candidate variables on a random subset of the data (i.e. how many ICUSTAYS have at least one recording of each ITEMID)...

In [4]:
sub_limit = 100  ## subset size: number of ICUSTAYS randomly selected  

In [22]:
query = """
SELECT
  D.ITEMID,
  D.LABEL,
  COUNT(DISTINCT(II.ICUSTAY_ID)) AS STAY_COUNT,
  (COUNT(DISTINCT(II.ICUSTAY_ID))/(100)) AS FREQ
FROM
  physionet-data.mimiciii_clinical.chartevents C
INNER JOIN (
  SELECT
    *
  FROM (
    SELECT
      *
    FROM
      physionet-data.mimiciii_clinical.icustays I
    WHERE
      I.DBSOURCE='metavision'
      AND (I.FIRST_CAREUNIT='MICU'
        OR I.FIRST_CAREUNIT='SICU')
    ORDER BY
      RAND()
    LIMIT
      100) AS II_sub
  ORDER BY
    II_sub.SUBJECT_ID,
    II_sub.HADM_ID,
    II_sub.ICUSTAY_ID ) AS II
ON
  (C.SUBJECT_ID=II.SUBJECT_ID
    AND C.HADM_ID=II.HADM_ID
    AND C.ICUSTAY_ID=II.ICUSTAY_ID)
INNER JOIN
  physionet-data.mimiciii_clinical.d_items D
ON
  C.ITEMID=D.ITEMID
WHERE
  D.ITEMID IN (226754,
    227009,
    227010,
    223835)
GROUP BY
  D.ITEMID, D.LABEL"""
df = client.query(query).to_dataframe()
df

ITEMID                 LABEL  STAY_COUNT  FREQ
0  223835  Inspired O2 Fraction          49  0.49

In [5]:
%sql SELECT D.ITEMID, D.LABEL, COUNT(DISTINCT(II.ICUSTAY_ID)) AS STAY_COUNT, (COUNT(DISTINCT(II.ICUSTAY_ID))/(:sub_limit)) AS FREQ \
FROM CHARTEVENTS C \
INNER JOIN ( \
    SELECT * FROM ( \
        SELECT * \
        FROM ICUSTAYS I \
        WHERE I.DBSOURCE='metavision' AND (I.FIRST_CAREUNIT='MICU' or I.FIRST_CAREUNIT='SICU') \
        ORDER BY RAND() \
        LIMIT :sub_limit) AS II_sub \
    ORDER BY II_sub.SUBJECT_ID, II_sub.HADM_ID, II_sub.ICUSTAY_ID \
            ) AS II \
ON (C.SUBJECT_ID=II.SUBJECT_ID \
    AND C.HADM_ID=II.HADM_ID \
    AND C.ICUSTAY_ID=II.ICUSTAY_ID) \
INNER JOIN D_ITEMS D \
ON C.ITEMID=D.ITEMID \
WHERE D.ITEMID IN (226754, 227009, 227010, 223835) \
GROUP BY D.ITEMID

1 rows affected.


[(223835, 'Inspired O2 Fraction', 47L, Decimal('0.4700'))]

..and manually inspect the first few instances of each ITEM to confirm it contains the required data:

In [23]:
query = """
SELECT
  *
FROM
  physionet-data.mimiciii_clinical.chartevents
WHERE
  ITEMID=223835
LIMIT 5"""
df = client.query(query).to_dataframe()
df

ROW_ID  SUBJECT_ID  HADM_ID  ICUSTAY_ID  ITEMID           CHARTTIME  \
0  10869474       51039   165913      296600  223835 2129-07-04 17:00:00   
1   5770054       40548   168670      260223  223835 2156-08-06 01:32:00   
2  27669581       85230   153781      220628  223835 2194-01-03 10:00:00   
3   2443719       21630   145084      238858  223835 2194-09-04 06:32:00   
4   2487501       21630   145084      238858  223835 2194-09-05 18:56:00   

            STORETIME     CGID VALUE  VALUENUM VALUEUOM  WARNING  ERROR  \
0 2129-07-04 18:29:00  14913.0    40      40.0     None        0      0   
1                 NaT      NaN    40      40.0     None        0      0   
2 2194-01-03 10:01:00  17857.0    45      45.0     None        1      0   
3                 NaT      NaN    40      40.0     None        0      0   
4                 NaT      NaN    40      40.0     None        0      0   

  RESULTSTATUS STOPPED  
0         None    None  
1         None    None  
2         None    None  
3         None    None  
4         None    None

In [6]:
%sql SELECT * FROM CHARTEVENTS WHERE ITEMID=223835 LIMIT 5 

5 rows affected.


[(335L, 34, 144319, 290505, 223835, datetime.datetime(2191, 2, 23, 7, 31), datetime.datetime(2191, 2, 23, 7, 35), 16924, '60', 60.0, None, 0, 0, None, None),
 (430L, 34, 144319, 290505, 223835, datetime.datetime(2191, 2, 23, 11, 0), datetime.datetime(2191, 2, 23, 11, 4), 14913, '60', 60.0, None, 0, 0, None, None),
 (706L, 36, 165660, 241249, 223835, datetime.datetime(2134, 5, 12, 7, 9), datetime.datetime(2134, 5, 12, 7, 9), 17525, '100', 100.0, None, 0, 0, None, None),
 (789L, 36, 165660, 241249, 223835, datetime.datetime(2134, 5, 12, 12, 0), datetime.datetime(2134, 5, 12, 13, 56), 17525, '100', 100.0, None, 0, 0, None, None),
 (877L, 36, 165660, 241249, 223835, datetime.datetime(2134, 5, 12, 16, 13), datetime.datetime(2134, 5, 12, 16, 27), 18428, '100', 100.0, None, 0, 0, None, None)]

*For example ITEMID 223835 (Inspired O2 Fraction) contains numeric fractional data, and is measured with a reasonably high frequency (~0.4 to 0.6). We connclude that this is a relevant ITEM.*	

#### By the above procedure we identify the following ITEMIDS corresponding to the required variables:

* Some ITEMIDS may not be in (frequent) use in the database - we select them anyway for completeness.
* Urine output may be located in either CHARTEVENTS or OUTPUTEVENTS (we check both).

**As a single list this is** (220739, 223900, 223901, 226755, 226756, 226757, 226758, 227011, 227012, 227013, 227014,228112, 220615, 226752, 227005, 223791, 227881, 227519, 227059, 220640, 227464, 227442, 226772, 226535, 220645, 226534, 226776, 224826, 226759, 227443,220227, 220277, 226860,226861,226862,226863,226865,228232, 225624, 227000, 227001, 223838, 224832, 224391, 227810,223837, 224829, 226754, 227009, 227010,223835, 220210, 224688, 224689, 224690, 226770,227039,227516,220224,220235,226062,226063,227036, 223761, 223762, 224027, 220045, 220228, 220339, 224699, 224700, 220050, 220059, 220179, 224167, 225309, 227243, 226850, 226852, 228151) ** for CHARTEVENTS.**

** And ** (226566, 226627, 226631) **for OUTPUTEVENTS (urine output only).**

-------------------------------------
## (B) Extracting the data

Having located the relevant ITEMIDs we now:

* Calculate their usage frequency from a larger random sample of ICUSTAYS
* Define a cuttoff frequency
* Extract and save all measurements of the remaining variables

In [7]:
sub_limit=1000  ## size of random sample

As before we calculate how many ICUSTAYS have at least one measurement of each ITEM, and convert this to an occurence frequnecy (FREQ). This time we calculate for all ITEMIDs simultaneoulsy, and sort the results by ascending occurence frequency. For CHARTEVENTS:

In [14]:
query = """
SELECT
  D.ITEMID,
  D.LABEL,
  COUNT(DISTINCT(II.ICUSTAY_ID)) AS STAY_COUNT,
  (COUNT(DISTINCT(II.ICUSTAY_ID))/8000) AS FREQ
FROM
  physionet-data.mimiciii_clinical.chartevents C
INNER JOIN (
  SELECT
    *
  FROM (
    SELECT
      *
    FROM
      physionet-data.mimiciii_clinical.icustays I
    WHERE
      I.DBSOURCE='metavision'
      AND (I.FIRST_CAREUNIT='MICU'
        OR I.FIRST_CAREUNIT='SICU')
    ORDER BY
      RAND()
    LIMIT
      8000) AS II_sub
  ORDER BY
    II_sub.SUBJECT_ID,
    II_sub.HADM_ID,
    II_sub.ICUSTAY_ID ) AS II
ON
  (C.SUBJECT_ID=II.SUBJECT_ID
    AND C.HADM_ID=II.HADM_ID
    AND C.ICUSTAY_ID=II.ICUSTAY_ID)
INNER JOIN
  physionet-data.mimiciii_clinical.d_items D
ON
  C.ITEMID=D.ITEMID
WHERE
  D.ITEMID IN (220739, 223900, 223901, 226755, 226756, 226757, 226758, 227011, 227012, 227013,
    227014, 228112, 220615, 226752, 227005, 223791, 227881, 227519, 227059, 220640, 227464,
    227442, 226772, 226535, 220645, 226534, 226776, 224826, 226759, 227443, 220227, 220277,
    226860, 226861, 226862, 226863, 226865, 228232, 225624, 227000, 227001, 223838, 224832,
    224391, 227810, 223837, 224829, 226754, 227009, 227010, 223835, 220210, 224688, 224689,
    224690, 226770, 227039, 227516, 220224, 220235, 226062, 226063, 227036, 223761, 223762,
    224027, 220045, 220228, 220339, 224699, 224700, 220050, 220059, 220179, 224167, 225309,
    227243, 226850, 226852, 228151)
GROUP BY
  D.ITEMID,
  D.LABEL
ORDER BY
  FREQ
"""
df = client.query(query).to_dataframe()
df

ITEMID                                 LABEL  STAY_COUNT      FREQ
0   227039                          PO2_ApacheIV           1  0.000125
1   227010                         FiO2_ApacheIV           1  0.000125
2   227036                         PCO2_ApacheIV           1  0.000125
3   227000                          BUN_ApacheIV           2  0.000250
4   227013                     GcsScore_ApacheIV           2  0.000250
5   227519                 Urine output_ApacheIV           2  0.000250
6   227001                     BunScore_ApacheIV           2  0.000250
7   227005                   Creatinine_ApacheIV           2  0.000250
8   227059                   UrineScore_ApacheIV           2  0.000250
9   226754                     FiO2ApacheIIValue           7  0.000875
10  226752               CreatinineApacheIIValue           8  0.001000
11  226759                     HCO3ApacheIIValue           8  0.001000
12  226776                   SodiumApacheIIValue           9  0.001125
13  226758                GCSVerbalApacheIIValue           9  0.001125
14  226755                      GcsApacheIIScore           9  0.001125
15  226772                PotassiumApacheIIValue           9  0.001125
16  226756                   GCSEyeApacheIIValue           9  0.001125
17  226757                 GCSMotorApacheIIValue           9  0.001125
18  227881                           Pain (0-10)          12  0.001500
19  227243  Manual Blood Pressure Systolic Right          37  0.004625
20  224167   Manual Blood Pressure Systolic Left          49  0.006125
21  220059    Pulmonary Artery Pressure systolic         115  0.014375
22  228232                 PAR-Oxygen saturation         181  0.022625
23  223762                   Temperature Celsius         314  0.039250
24  225309                       ART BP Systolic         369  0.046125
25  224829                       Trach Tube Type         415  0.051875
26  227516                    PO2 (Mixed Venous)         439  0.054875
27  227810                          ETT Re-taped         874  0.109250
28  226063                    Venous O2 Pressure         922  0.115250
29  226062                   Venous CO2 Pressure         922  0.115250
..     ...                                   ...         ...       ...
32  220227                Arterial O2 Saturation        1476  0.184500
33  227464               Potassium (whole blood)        1613  0.201625
34  224700                      Total PEEP Level        1837  0.229625
35  220050      Arterial Blood Pressure systolic        2428  0.303500
36  223838                          ETT Location        2485  0.310625
37  223837                         ETT Size (ID)        2490  0.311250
38  224832                              ETT Type        2501  0.312625
39  224688                Respiratory Rate (Set)        2576  0.322000
40  224690              Respiratory Rate (Total)        2810  0.351250
41  224689        Respiratory Rate (spontaneous)        2890  0.361250
42  220339                              PEEP set        2918  0.364750
43  220235                 Arterial CO2 Pressure        3514  0.439250
44  220224                  Arterial O2 pressure        3514  0.439250
45  223835                  Inspired O2 Fraction        3776  0.472000
46  223791                            Pain Level        7190  0.898750
47  220228                            Hemoglobin        7714  0.964250
48  225624                                   BUN        7743  0.967875
49  220615                            Creatinine        7746  0.968250
50  227443                          HCO3 (serum)        7746  0.968250
51  220645                        Sodium (serum)        7747  0.968375
52  227442                     Potassium (serum)        7749  0.968625
53  220179  Non Invasive Blood Pressure systolic        7822  0.977750
54  224027                      Skin Temperature        7838  0.979750
55  223761                Temperature Fahrenheit        7857  0.982125
56  223901                  

In [15]:
ITEMIDS = df[df['FREQ']>=0.015]['ITEMID']  ## cutoff = 0.01
ITEMIDS_TOREMOVE = df[df['FREQ']<0.015]['ITEMID']  ## remove these from variable mapping
len(ITEMIDS), len(ITEMIDS_TOREMOVE)

(40, 22)

..and for OUTPUTEVENTS:

In [26]:
query = """
SELECT
  D.ITEMID,
  D.LABEL,
  COUNT(DISTINCT(II.ICUSTAY_ID)) AS STAY_COUNT,
  (COUNT(DISTINCT(II.ICUSTAY_ID))/3000) AS FREQ
FROM
  physionet-data.mimiciii_clinical.outputevents C
INNER JOIN (
  SELECT
    *
  FROM (
    SELECT
      *
    FROM
      physionet-data.mimiciii_clinical.icustays I
    WHERE
      I.DBSOURCE='metavision'
      AND (I.FIRST_CAREUNIT='MICU'
        OR I.FIRST_CAREUNIT='SICU')
    ORDER BY
      RAND()
    LIMIT
      3000) AS II_sub
  ORDER BY
    II_sub.SUBJECT_ID,
    II_sub.HADM_ID,
    II_sub.ICUSTAY_ID ) AS II
ON
  (C.SUBJECT_ID=II.SUBJECT_ID
    AND C.HADM_ID=II.HADM_ID
    AND C.ICUSTAY_ID=II.ICUSTAY_ID)
INNER JOIN
  physionet-data.mimiciii_clinical.d_items D
ON
  C.ITEMID=D.ITEMID
WHERE
  D.ITEMID IN (226566, 226627, 226631)
GROUP BY
  D.ITEMID,
  D.LABEL
ORDER BY
  FREQ
"""
df = client.query(query).to_dataframe()
df

ITEMID       LABEL  STAY_COUNT   FREQ
0  226631  PACU Urine          16  0.016
1  226627    OR Urine         131  0.131

**Note:** we find that the 'Urine Output' ITEMs that we identified are not in frequent use. The difficulty of identifying urine in MIMIC has been previoulsy noted by others. We accept that we canot use 'Urine Output' in our analysis and do not attempt further investigation.  

We now store the CHARTEVENTS query results into a dataframe, and remove those that are only recorded infrequently. This is done to simplify the subsequent analysis (and reduce the required number of checks on data integrity), but we aknowledge that it will result in a small amount of missing data. We define a minimum usage frequency of 0.01 (1%).

In [6]:
print("There are %d infrequent ITEMS to remove from the variable mapping." %len(ITEMIDS_TOREMOVE))

There are 22 infrequent ITEMS to remove from the variable mapping.


In [18]:
variable_mapping = dict()

variable_mapping['fio2'] = [226754, 227009, 227010,223835]
variable_mapping['resp'] = [220210, 224688, 224689, 224690]
variable_mapping['po2'] = [226770,227039,227516,220224]  ## 227516 is venous - excluded in subsequent script.
variable_mapping['pco2'] = [220235,226062,226063,227036]  ## 226062,226063 are venous - excluded in subsequent script.

variable_mapping['temp'] = [223761, 223762, 224027] 
variable_mapping['hr'] = [220045]
variable_mapping['bp'] = [220050, 220059, 220179, 224167, 225309, 227243, 226850, 226852, 228151] ## 228151 is diastolic - excluded in subsequent script.
variable_mapping['k'] = [220640, 227464, 227442, 226772, 226535]
variable_mapping['na'] = [220645, 226534, 226776]
variable_mapping['hco3'] = [224826, 226759, 227443]
variable_mapping['spo2'] = [220227, 220277, 226860,226861,226862,226863,226865,228232]
variable_mapping['bun'] = [225624, 227000, 227001]
variable_mapping['airway'] = [223838, 224832, 224391, 227810,223837, 224829]
variable_mapping['gcs'] = [220739, 223900, 223901, 226755, 226756, 226757, 226758, 227011, 227012, 227013, 227014,228112]
variable_mapping['creatinine'] = [220615, 226752, 227005]
variable_mapping['pain'] = [223791, 227881]
variable_mapping['urine'] = [] #[227519, 227059]
variable_mapping['haemoglobin'] = [220228]
variable_mapping['peep'] = [220339, 224699, 224700]
                        
for var in variable_mapping:
    variable_mapping[var] = [itd for itd in variable_mapping[var] if itd not in list(ITEMIDS_TOREMOVE)]
        
print(variable_mapping)

{'fio2': [227009, 223835], 'resp': [220210, 224688, 224689, 224690], 'po2': [226770, 227516, 220224], 'pco2': [220235, 226062, 226063], 'temp': [223761, 223762, 224027], 'hr': [220045], 'bp': [220050, 220179, 225309, 226850, 226852, 228151], 'k': [220640, 227464, 227442, 226535], 'na': [220645, 226534], 'hco3': [224826, 227443], 'spo2': [220227, 220277, 226860, 226861, 226862, 226863, 226865, 228232], 'bun': [225624], 'airway': [223838, 224832, 224391, 227810, 223837, 224829], 'gcs': [220739, 223900, 223901, 227011, 227012, 227014, 228112], 'creatinine': [220615], 'pain': [223791], 'urine': [], 'haemoglobin': [220228], 'peep': [220339, 224699, 224700]}


In [19]:
orig_mapping = {'urine': [], 'pain': [223791], 'temp': [223761, 223762, 224027], 'hr': [220045], 'fio2': [227009, 223835], 'resp': [220210, 224688, 224689, 224690], 'airway': [223838, 224832, 224391, 227810, 223837, 224829], 'po2': [226770, 227039, 227516, 220224], 'hco3': [224826, 227443], 'peep': [220339, 224699, 224700], 'gcs': [220739, 223900, 223901, 227011, 227012, 227014, 228112], 'pco2': [220235, 226062, 226063], 'na': [220645, 226534], 'bun': [225624], 'bp': [220050, 220179, 225309, 226850, 226852, 228151], 'creatinine': [220615], 'k': [220640, 227464, 227442, 226535], 'spo2': [220227, 220277, 226860, 226861, 226862, 226863, 226865, 228232], 'haemoglobin': [220228]}
for var in variable_mapping:
    #print(var, set(orig_mapping[var])==set(variable_mapping[var]))
    if set(orig_mapping[var])!=set(variable_mapping[var]):
        print(var, set(orig_mapping[var]), set(variable_mapping[var]))

po2 {220224, 226770, 227516, 227039} {220224, 226770, 227516}


In [30]:
count = 0
for item in variable_mapping.values():
    for ID in item:
        count += 1
        if ID not in list(ITEMIDS):
            print(ID)
print(count)

226754
227009
227010
226770
227039
227036
224167
227243
226850
226852
228151
220640
226772
226535
226776
224826
226759
226860
226861
226862
226863
226865
227000
227001
226755
226756
226757
226758
227011
227012
227013
227014
228112
226752
227005
227881
224699
78


#### Finally we extract the data from CHARTEVENTS for all the selected ITEMIDS:

In [24]:
list_of_ids = ITEMIDS
format_strings = ','.join(['%s'] * len(list_of_ids))

In [22]:
partial_pull_query0 ="""SELECT C.SUBJECT_ID, C.HADM_ID, C.ICUSTAY_ID, C.ITEMID, C.CHARTTIME, C.VALUE, C.VALUENUM, C.VALUEUOM, II.INTIME, II.OUTTIME, II.LOS
FROM CHARTEVENTS C 
INNER JOIN ICUSTAYS II
ON (C.SUBJECT_ID=II.SUBJECT_ID 
    AND C.HADM_ID=II.HADM_ID 
    AND C.ICUSTAY_ID=II.ICUSTAY_ID)  
WHERE II.DBSOURCE='metavision' 
AND (II.FIRST_CAREUNIT='MICU' or II.FIRST_CAREUNIT='SICU') """
#AND II.ICUSTAY_ID=%d"""

partial_pull_query1="""
   AND C.ITEMID in """

In [ ]:
query = """
SELECT C.SUBJECT_ID, C.HADM_ID, C.ICUSTAY_ID, C.ITEMID, C.CHARTTIME, C.VALUE, C.VALUENUM, C.VALUEUOM, II.INTIME, II.OUTTIME, II.LOS
FROM physionet-data.mimiciii_clinical.chartevents C 
INNER JOIN physionet-data.mimiciii_clinical.icustays II
ON (C.SUBJECT_ID=II.SUBJECT_ID 
AND C.HADM_ID=II.HADM_ID 
AND C.ICUSTAY_ID=II.ICUSTAY_ID)  
WHERE II.DBSOURCE='metavision' 
AND (II.FIRST_CAREUNIT='MICU' or II.FIRST_CAREUNIT='SICU') 
AND C.ITEMID in (228232, 223762, 225309, 224829, 227516, 227810, 226063, 226062, 226534, 224391, 220227, 227464, 224700, 220050, 223838, 223837, 224832, 224688, 224690, 224689, 220339, 220235, 220224, 223835, 223791, 220228, 225624, 220615, 227443, 220645, 227442, 220179, 224027, 223761, 223901, 220739, 223900, 220277, 220210, 220045)"""
df = client.query(query).to_dataframe()
df

##  executed through bigquery and saved to test.interesting_chartevents table

#### We proceed in batches of 3000 patients and then clean up at the end (this is probably not necessary):

In [21]:
## This should not be necessary in an un-corrupted database.
## icustays = [i for i in icustays if i not in (249026, 254172)]

#### If joining the batched results was successful we can safely remove the batch files:

#### We now need to extract D.Label and D.Unitname from D_Items and join them to the results table:

In [5]:
data = pd.read_pickle('interesting_chartevents.pickle')

In [6]:
ditems_query = """SELECT ITEMID, LABEL, UNITNAME FROM test.d_items WHERE ITEMID in (228232, 223762, 225309, 224829, 227516, 227810, 226063, 226062, 226534, 224391, 220227, 227464, 224700, 220050, 223838, 223837, 224832, 224688, 224690, 224689, 220339, 220235, 220224, 223835, 223791, 220228, 225624, 220615, 227443, 220645, 227442, 220179, 224027, 223761, 223901, 220739, 223900, 220277, 220210, 220045)"""
df = client.query(ditems_query).to_dataframe()
df

ITEMID                                 LABEL  UNITNAME
0   227516                    PO2 (Mixed Venous)      mmHg
1   227442                     Potassium (serum)      None
2   227443                          HCO3 (serum)      None
3   227464               Potassium (whole blood)      None
4   225624                                   BUN      None
5   220615                            Creatinine      None
6   220645                        Sodium (serum)      None
7   220224                  Arterial O2 pressure      mmHg
8   220227                Arterial O2 Saturation         %
9   220228                            Hemoglobin      g/dl
10  220235                 Arterial CO2 Pressure      mmHg
11  226062                   Venous CO2 Pressure      mmHg
12  226063                    Venous O2 Pressure      mmHg
13  226534                  Sodium (whole blood)      None
14  224688                Respiratory Rate (Set)  insp/min
15  224689        Respiratory Rate (spontaneous)  insp/min
16  224690              Respiratory Rate (Total)  insp/min
17  224700                      Total PEEP Level     cmH2O
18  224391                   ETT Mark (location)      None
19  227810                          ETT Re-taped      None
20  220210                      Respiratory Rate  insp/min
21  224829                       Trach Tube Type      None
22  224832                              ETT Type      None
23  220277           O2 saturation pulseoxymetry         %
24  220339                              PEEP set     cmH2O
25  223835                  Inspired O2 Fraction      None
26  223837                         ETT Size (ID)      None
27  223838                          ETT Location      None
28  220739                     GCS - Eye Opening      None
29  223900                 GCS - Verbal Response      None
30  223901                  GCS - Motor Response      None
31  223791                            Pain Level      None
32  224027                      Skin Temperature      None
33  228232                 PAR-Oxygen saturation      None
34  220045                            Heart Rate       bpm
35  220050      Arterial Blood Pressure systolic      mmHg
36  220179  Non Invasive Blood Pressure systolic      mmHg
37  223761                Temperature Fahrenheit        ?F
38  223762                   Temperature Celsius        ?C
39  225309                       ART BP Systolic      mmHg

In [7]:
len(data), len(data['ITEMID'].unique()), len(df)

(10814977, 40, 40)

In [8]:
data = pd.merge(data, df, on='ITEMID')

----------------------------------------------------------------------------------------------
## (C) Post-processing of data.

Having extracted the main data we perform some post-processing to facilitate analysis. 

['SUBJECT_ID', 'HADM_ID', 'ICUSTAY_ID', 'ITEMID', 'CHARTTIME', 'VALUE', 'VALUENUM', 'VALUEUOM', 'INTIME', 'OUTTIME', 'LOS', 'D.LABEL', 'D.UNITNAME']


In [9]:
data = data.rename(columns={'SUBJECT_ID':'C.SUBJECT_ID',
                            'HADM_ID':'C.HADM_ID',
                            'ICUSTAY_ID':'C.ICUSTAY_ID',
                            'ITEMID':'D.ITEMID',
                            'CHARTTIME':'C.CHARTTIME',
                            'VALUE':'C.VALUE',
                            'VALUENUM':'C.VALUENUM',
                            'VALUEUOM':'C.VALUEUOM',
                            'INTIME':'II.INTIME',
                            'OUTTIME':'II.OUTTIME',
                            'LOS':'II.LOS',
                            'LABEL':'D.LABEL',
                            'UNITNAME':'D.UNITNAME'})

In [10]:
number_of_stays = len(data['C.ICUSTAY_ID'].unique())
print("There are %d rows in the data. "%(len(data)))
print( "There are %d intensive care stays." %number_of_stays)

There are 10814977 rows in the data. 
There are 14432 intensive care stays.


In [11]:
data.to_pickle('interesting_chartevents_with_labels.pickle')

In [13]:
del data

#### We add the following columns to the data:

* ['final_4hr'] : 1 if measurement is from final 4 hours of patients stay
* ['final_24hr'] : 1 if measurement is from final 24 hours of patients stay
* ['hrs_bd'] : float giving number of hours before discharge that measurement was taken (can filter on this column later)

In [12]:
all_data = pd.read_pickle("interesting_chartevents_with_labels.pickle")

In [14]:
all_data['hrs_bd'] = (all_data['II.OUTTIME'] - all_data['C.CHARTTIME'])/float(60**2)
#all_data.save('mimic_all_data')  

In [31]:
row = all_data.iloc[0]
a = row['II.OUTTIME'] - row['C.CHARTTIME']

In [24]:
all_data = all_data.drop(columns='final_14400hr')

In [25]:
HR = 4 ## number of hours before end of ICUSTAY 
SECS = HR * (60.**2)
all_data['final_%dhr'%HR] = all_data['II.OUTTIME'] - all_data['C.CHARTTIME']
all_data['final_%dhr'%HR] = all_data['final_%dhr'%HR].apply(lambda row: (row.total_seconds() <= SECS)*1)
#all_data.save('mimic_all_data')            

In [28]:
HR = 24 ## number of hours before end of ICUSTAY 
SECS = HR * (60.**2)
all_data['final_%dhr'%HR] = all_data['II.OUTTIME'] - all_data['C.CHARTTIME']
all_data['final_%dhr'%HR] = all_data['final_%dhr'%HR].apply(lambda row: (row.total_seconds() <= SECS)*1)
#all_data.save('mimic_all_data')            

In [29]:
all_data.to_pickle('interesting_chartevents_with_labels_with_hour_window.pickle')

#### Merging data extraction with cohort..

We now add columns for cohort identification, and filtering based on outcome. Main cohort consists of the first ICUSTAY of each hospital admission (should be >13000 stays).

From this cohort we are interested in ICUSTAYS that have good (1) and bad (0) outcome.
The are two types of bad outcome: (A) in-hospital death, (B) readmission to ICU (during same hospital admission).

The above abstraction is not fool-proof. For example:
* patients may die outside of hospital for related reasons
* readmission may be linked but occur on different stay
* in-hopistal death may be unrelated to ICU discharge
* etc

We add the following columns to the data frame: 

* ['cohort']: binary flag. 1 indicates that ICUSTAY is part of cohort (i.e. first or only stay of a hospital admission).
* ['outcome']: binary flag. 1 indicates good outcome (survival with no readmission). 0 indicates bad outcome (death or readmission).
* ['in_h_death']: binary flag. 1 for death. 0 for survival.
* ['in_icu_death']: binary flag. 1 for death. 0 for survival.
* ['readmit']: integer. Number of readmissions to icu during same hospital admission.

*Note: there are fewer HADMs than in cohort_selection_mimic.ipynb, since not all patients have chartevents data.*

In [3]:
all_data = pd.read_pickle('interesting_chartevents_with_labels_with_hour_window.pickle')

In [4]:
f = open('first_stays.pkl', 'rb')
first_stays = pickle.load(f)
f.close()

f = open('moratlities.pkl', 'rb')
mortalities = pickle.load(f)
f.close()

f = open('stay_counts.pkl', 'rb')
stay_counts = pickle.load(f)
f.close()

f = open('icu_deaths.pkl', 'rb')
ic_deaths = pickle.load(f)
f.close()

In [5]:
print( "Adding cohort column...")
all_data['cohort'] = all_data['C.HADM_ID'].apply(lambda row: first_stays[row])
all_data['cohort'] = (all_data['cohort']==all_data['C.ICUSTAY_ID'])*1

Adding cohort column...


In [12]:
print( "Adding in hospital column...")
all_data['in_h_death'] = all_data['C.HADM_ID'].isin(mortalities)

Adding in hospital column...


In [14]:
print( "Adding in icu death column...")
all_data['in_icu_death'] = all_data['C.ICUSTAY_ID'].isin(ic_deaths)*1

Adding in icu death column...


In [16]:
print( "Adding readmission column...")
all_data['readmit'] = all_data['C.HADM_ID'].apply(lambda hadmid: stay_counts[hadmid] - 1)

Adding readmission column...


In [17]:
print( "Adding outcome column...")
all_data['outcome'] = all_data['C.HADM_ID'].apply(lambda hadmid: 1 if (hadmid not in mortalities and stay_counts[hadmid]==1) else 0)

print( 'finish adding new columns, saving data frame..')

Adding outcome column...
finish adding new columns, saving data frame..


In [20]:
all_data.to_pickle('final_interesting_chartevents.pickle')

In [19]:
print( "There are %d unique ICU stays, of which" %len(all_data['C.ICUSTAY_ID'].unique()))
print( "%d are in the cohort." %(len(all_data[all_data['cohort']==1]['C.ICUSTAY_ID'].unique())))

There are 14432 unique ICU stays, of which
13604 are in the cohort.


In [25]:
all_data[all_data['D.ITEMID']==223761]

C.SUBJECT_ID  C.HADM_ID  C.ICUSTAY_ID  D.ITEMID         C.CHARTTIME  \
1163266         48974     155902        206851    223761 2172-02-18 13:15:00   
1163267         82973     183701        208946    223761 2110-03-18 16:00:00   
1163268         63509     166932        275627    223761 2121-02-23 20:00:00   
1163269         91561     182755        231044    223761 2113-09-01 14:00:00   
1163270         78263     173396        225369    223761 2159-01-11 04:07:00   
1163271         67281     193371        280802    223761 2130-03-05 08:00:00   
1163272         76319     141797        255061    223761 2108-08-16 07:00:00   
1163273         51551     143320        292648    223761 2151-04-22 08:00:00   
1163274         68579     194906        276559    223761 2195-08-22 06:00:00   
1163275          8492     118470        225777    223761 2117-07-15 00:00:00   
1163276         28109     142713        271669    223761 2155-05-01 00:00:00   
1163277         94864     168788        288166    223761 2179-12-11 12:00:00   
1163278         81425     120766        296608    223761 2120-06-24 16:00:00   
1163279         68890     124624        267410    223761 2178-03-23 16:00:00   
1163280         95895     115708        233904    223761 2130-06-30 18:00:00   
1163281         74794     169213        264055    223761 2138-07-20 12:00:00   
1163282         40595     116518        276601    223761 2144-10-23 12:00:00   
1163283         65180     194713        215282    223761 2114-12-07 08:00:00   
1163284         77427     163354        244787    223761 2139-11-19 04:00:00   
1163285         52967     134043        268509    223761 2200-04-15 12:00:00   
1163286         95201     192304        274147    223761 2174-05-05 12:00:00   
1163287         72775     147873        296871    223761 2170-01-19 04:00:00   
1163288         65837     184409        251654    223761 2104-11-10 12:00:00   
1163289         57642     131270        259835    223761 2152-08-14 16:00:00   
1163290         98038     118038        209310    223761 2197-09-12 16:00:00   
1163291         91295     158759        202639    223761 2163-04-24 00:00:00   
1163292         74022     150341        298194    223761 2193-06-04 20:00:00   
1163293         44059     198015        285771    223761 2127-07-29 04:00:00   
1163294         46320     113335        206856    223761 2131-05-12 12:00:00   
1163295         85892     187089        209764    223761 2181-08-28 16:00:00   
...               ...        ...           ...       ...                 ...   
1501223         94987     193169        229148    223761 2172-04-29 19:00:00   
1501224         96176     176226        216151    223761 2144-05-09 00:00:00   
1501225         91738     167406        217105    223761 2196-11-23 08:00:00   
1501226         68377     110053        291656    223761 2188-11-27 00:00:00   
1501227         58702     114246        287187    223761 2114-11-16 04:00:00   
1501228         41192     179885        289378    223761 2117-03-20 20:00:00   
1501229         99650     199859        207220    223761 2157-01-23 00:00:00   
1501230         93336     193535        249608    223761 2119-08-12 20:00:00   
1501231         42009     147209        204287    223761 2110-11-30 08:55:00   
1501232         87572     111160        237121    223761 2141-06-28 00:00:00   
1501233         27586     138041        276306    223761 2115-06-22 20:00:00   
1501234         47709     197058        293368    223761 2147-08-17 20:00:00   
1501235         49380     110837        241303    223761 2105-04-07 12:00:00   
1501236         41192     110739        227716    223761 2117-03-31 12:00:00   
1501237         46178     122231        289118    223761 2134-12-07 00:00:00   
1501238         91463     190015        207409    223761 2151-12-27 00:00:00   
1501239         45698     188554        276981    223761 2113-06-15 05:00:00   
1501240         63569     146083        285211    223761 2160-12-06 16:00:00   
1501241  

Note: this cohort size will be reduced by further processing in subsequent scripts.